### ISSUE TITLE
use gcc6 on travis

### ISSUE THREAD

**Issue by rurban** [perl11/cperl#319]
it is much faster locally, all the new __builtin_arith_overflow intrinsics.
find a docker or ubuntu repo.

Issue: travis-ci/apt-package-whitelist#2294
Packages: https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test

```
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
```
